"""Rule-based mapping of interest x branch -> workshop project.

Each project: title, pitch (one line), variation (one line, branch specific), steps (3).
"""

PROJECTS = {
    ("Placements", "CSE/IT"): {
        "title": "Resume-to-Interview Coach",
        "pitch": "Paste your resume, get the 10 questions an interviewer will actually ask.",
        "variation": "CSE/IT twist: it also drills you on DSA and system-design follow-ups from your projects.",
        "steps": [
            "Parse a resume PDF into clean text with a 20-line Python script",
            "Prompt an LLM to generate role-specific interview questions",
            "Score your spoken answers and get a one-line improvement tip",
        ],
    },
    ("Placements", "ECE/EEE"): {
        "title": "Core-Company Aptitude Drill Bot",
        "pitch": "A bot that generates fresh aptitude and core-subject questions in your weak areas.",
        "variation": "ECE/EEE twist: question bank tuned to signals, circuits and embedded C.",
        "steps": [
            "Feed it a list of topics you keep getting wrong",
            "Generate a timed 10-question drill with an LLM",
            "Track your accuracy per topic in a tiny local dashboard",
        ],
    },
    ("Placements", "Mech/Civil/Other"): {
        "title": "Job Description Decoder",
        "pitch": "Paste any JD and see exactly which skills to highlight and which to learn this month.",
        "variation": "Mech/Civil twist: maps CAD, GD&T and site-management keywords to your coursework.",
        "steps": [
            "Scrape or paste 5 job descriptions you like",
            "Extract and cluster skills with an LLM",
            "Generate a 4-week prep plan and a tailored resume summary",
        ],
    },
    ("Startups", "CSE/IT"): {
        "title": "Campus Canteen Order Predictor",
        "pitch": "Predict tomorrow's rush items so the canteen stops running out of samosas by 11 AM.",
        "variation": "CSE/IT twist: expose it as a REST API the canteen can hit from a phone.",
        "steps": [
            "Collect 2 weeks of sales data in a simple CSV",
            "Train a lightweight forecasting model in a notebook",
            "Wrap it in an API and show predictions on one page",
        ],
    },
    ("Startups", "ECE/EEE"): {
        "title": "Smart Hostel Energy Meter",
        "pitch": "Spot which room is burning power and nudge them before the hostel bill explodes.",
        "variation": "ECE/EEE twist: read a real sensor stream from an ESP32 and detect anomalies.",
        "steps": [
            "Simulate (or stream) per-room power readings",
            "Detect unusual usage with a simple anomaly model",
            "Send a WhatsApp-style nudge message generated by an LLM",
        ],
    },
    ("Startups", "Mech/Civil/Other"): {
        "title": "Site Photo to Progress Report",
        "pitch": "Click a photo of a construction or workshop site and get a one-page progress update.",
        "variation": "Mech/Civil twist: trained prompts for scaffolding, formwork and machining stages.",
        "steps": [
            "Capture 3 to 5 photos of a site or lab bench",
            "Describe each photo with a vision model",
            "Compile a dated progress report with an LLM",
        ],
    },
    ("Health", "CSE/IT"): {
        "title": "Mess Food Nutrition Tracker",
        "pitch": "Photograph your mess plate and get calories, protein and a nicer suggestion for tomorrow.",
        "variation": "CSE/IT twist: store history in a database and chart your week.",
        "steps": [
            "Identify food items on a plate with a vision model",
            "Look up nutrition values from a small open dataset",
            "Show a weekly trend chart with one actionable tip",
        ],
    },
    ("Health", "ECE/EEE"): {
        "title": "Symptom Triage Chatbot",
        "pitch": "A chatbot that asks the right follow-up questions and tells you if it is clinic-worthy.",
        "variation": "ECE/EEE twist: plug in a pulse-oximeter or heart-rate sensor reading as an input.",
        "steps": [
            "Design a safe, non-diagnostic conversation flow",
            "Add sensor readings as structured context for the LLM",
            "Output a clear 'rest / visit clinic / urgent' recommendation",
        ],
    },
    ("Health", "Mech/Civil/Other"): {
        "title": "Posture Check Buddy",
        "pitch": "Your webcam watches your study posture and pings you before the back pain starts.",
        "variation": "Mech/Civil twist: compute joint angles with simple biomechanics rules.",
        "steps": [
            "Detect body keypoints from a webcam with a pose model",
            "Compute neck and back angles and set thresholds",
            "Log slouch events and show a daily posture score",
        ],
    },
    ("Fun & games", "CSE/IT"): {
        "title": "Meme Caption Generator",
        "pitch": "Upload any photo from the hostel group and get 5 captions in your batch's humour.",
        "variation": "CSE/IT twist: fine-tune the voice with 20 of your own group-chat messages.",
        "steps": [
            "Describe an uploaded image with a vision model",
            "Generate captions in a chosen humour style",
            "Render the meme and share it with one tap",
        ],
    },
    ("Fun & games", "ECE/EEE"): {
        "title": "Gesture-Controlled Snake Game",
        "pitch": "Play Snake with hand gestures from your laptop camera, no keyboard needed.",
        "variation": "ECE/EEE twist: swap the camera for an accelerometer on a microcontroller.",
        "steps": [
            "Track hand landmarks with a pose/hand model",
            "Map gestures to up/down/left/right events",
            "Hook events into a simple game loop and add a scoreboard",
        ],
    },
    ("Fun & games", "Mech/Civil/Other"): {
        "title": "Cricket Shot Classifier",
        "pitch": "Upload a 5-second clip and find out if that was a cover drive or a wild slog.",
        "variation": "Mech/Civil twist: estimate bat speed and swing angle from frames.",
        "steps": [
            "Extract frames from a short video clip",
            "Classify the shot type with a small vision model",
            "Show the result with a confidence bar and a cheeky comment",
        ],
    },
}


def get_project(interest: str, branch: str) -> dict:
    return PROJECTS.get((interest, branch)) or PROJECTS[("Placements", "CSE/IT")]
